server:
  port: 3344

spring:
  application:
    name: cloud-config-center   #注册金Eureka服务器的微服务名
  cloud:
    config:
      server:
        git:
          uri: https://github.com/githubzys2017/springcloud-config    #github上面的git仓库名字
      ## 搜索目录
          search-paths:
            - springcloud-config
        default-label: master


eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
## 服务注册到Eureka地址