server:
  port: 3344

spring:
  application:
    name: cloud-config-center   #注册金Eureka服务器的微服务名
  cloud:
    config:
      server:
        git:
          uri: https://github.com/githubzys2017/springcloud-config    #github上面的git仓库名字
      ## 搜索目录
          search-paths:
            - springcloud-config
        default-label: master


## 服务注册到Eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka


# rabbitm的 相关配置
rabbitmq:
  host: localhost
  port: 15672
  username: guest
  password: guest


### rabbitmq相关配置，暴露bus刷新配置的端点
management:
  endpoints:
    web:
      exposure:
        include: 'bus-refresh'
